name: Pull Request

on:
  pull_request:
    branches: [main]

env:
  CACHE_VERSION: 1
  DENO_DIR: .deno

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    # Configure the Github Actions runner to use Linux-style line endings before
    # running the `actions/checkout` step due to a known issue with handling
    # Windows-style line endings (CRLF)
    # https://github.com/actions/checkout/issues/135
    - name: Set git to use LF
      if: matrix.os == 'windows-latest'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.DENO_DIR }}
        key: ${{ env.CACHE_VERSION }}-${{ hashFiles('lock.json') }}

    - name: Run all tests
      run: deno task test

    - name: Generate test coverage report
      run: deno coverage ./cov --lcov > cov.lcov

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        name: ${{ matrix.os }}
        files: cov.lcov

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check format
        run: deno fmt --check

      - name: Lint
        run: deno lint
